### ISSUE TITLE
toSoyCompatibleObjects in DefaultToSoyConverter does not support enumerations

### ISSUE THREAD

**Issue by solidjb** [matiwinnetou/spring-soy-view#58]
The current implementation of toSoyCompatibleObjects supports:

primitives (+ wrappers)
Strings
Maps
Iterables
Callables
Arrays

Would it be possible to add support for enumerations by converting them to Strings?
<pre><code>
if (obj.getClass().isEnum()) {
    return obj.toString();
}
</code></pre>

I have no problem making the change and submitting it, I just wanted to see if you had any objections to the idea first.

**Comment by matiwinnetou** [comment]
No, I have no objections. In fact it is a good idea, however keep in mind that this library is using a relatively old version of google closure. It would be also nice to upgrade to latest and provide support for a few new features. New library has a new concept of soy value converters.

**Comment by phasebash** [comment]
Should we use .toString() or .name()?

**Comment by matiwinnetou** [comment]
I think .name would make more sense but I don't know how one can do this via reflection?

**Comment by phasebash** [comment]
What is the question?  .name() is a method on enumerations which should return a String which represents the enum value.

**Comment by solidjb** [comment]
I suggested using toString because I wasn't sure if you could cast to an enumeration superclass. The Class class has the special method isEnum. That made me think that

<pre><code>obj instanceof Enum</code></pre>. Wouldn't work. However I verified that it does and a cast to Enum works too. Calling .name() after a cast is appropriate.

**Comment by solidjb** [comment]
<pre><code>
enum Spice {A, B, C, D} 
Object ob = Spice.A;     
Enum sp = (Enum) ob;    

assert sp instanceof Enum
​assert sp.name()​ == 'A'​​​​​​​​​​​​​
​</code></pre>

**Comment by solidjb** [comment]
I may look into upgrading the version of soy, but I would like to keep that separate from the enumeration support.  I have created an pull request for the enumeration support and will look into the upgrade shortly.

**Comment by solidjb** [comment]
Do you have an idea on when you will produce a point release? Is it possible to do this week?

**Comment by solidjb** [comment]
I was wondering if I could get an update on the status of releasing a version of spring-soy-view with this change in it.

**Comment by matiwinnetou** [comment]
That is not a problem, I can release a point version in no time. I will try to do this tonight.

**Comment by solidjb** [comment]
Thanks.  Let me know when its done, and I will close the issue.  Will it be available from maven central tonight as well?

**Comment by matiwinnetou** [comment]
released. 1.25.7

**Comment by matiwinnetou** [comment]
https://repo1.maven.org/maven2/pl/matisoft/spring-soy-view/1.25.7/

**Comment by solidjb** [comment]
Thanks.
